<?php
//module_invoke_all('wechat_message', $weObj);
function love2in1_wechat_message($weObj){
	if(!is_array($weObj->Message(''))){ // add default option
    $type = $weObj->getRev()->getRevType();
    switch($type) {
  	  case Wechat::MSGTYPE_EVENT:
  	    $event = $weObj->getRevEvent();
        if(!$event){
          break;
        }
  	    else if($event['event']=='subscribe'){
  	      $weObj->text(variable_get("wechat_follow_message", variable_get("wechat_default_message", 'Hi, WeChat!')));
  	    }
        else if($event['event']=='CLICK') {          
          if($event['key'] == 'GET_SONG'){
            // $news = ybzx_get_nodes($type = 'article', $counts = 1);
            // $weObj->news($news)->reply(); exit;
            $nodes = ybzx_get_nodes($content_type = 'article', $counts = 1, $type = 'nodes');
            $title = $nodes[0]->title;
            if(isset($nodes[0]->field_wechat_url[LANGUAGE_NONE][0]['value'])) {
              $musicurl = $nodes[0]->field_wechat_url[LANGUAGE_NONE][0]['value'];
            }else{
              $uri = $nodes[0]->field_mp3[LANGUAGE_NONE][0]['uri'];
              $musicurl = file_create_url($uri);
            }             
            //http://audio.liangyou.net/download.php?t=1&c=vmf&f=vmf131101.mp3
            $desc = "主爱合一,永不止息！love2in1 合一互动";
            $hgmusicurl = $musicurl;
            $weObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
            exit;            
          }
          if($event['key'] == '365'){
            $title = "恩典365:".date("m/d");
            $musicurl = 'http://w2.ysong.org/yage/60%E7%A6%8F%E9%9F%B3%E8%AF%81%E9%81%93/%E5%AF%87%E7%BB%8D%E6%81%A9/2014%E5%B9%B4%20'.urlencode(month2china()).'%E6%9C%88%E4%BB%BD/'.date('Ymd').'.mp3';;
            //http://audio.liangyou.net/download.php?t=1&c=vmf&f=vmf131101.mp3
            $desc = "主爱合一,永不止息！love2in1 合一互动";
            $hgmusicurl = $musicurl;
            $weObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
            exit;            
          }
          // $message = _wechat_menu_default_message($event);
          // $message && $weObj->text($message);
        }
  		  break;
    }
  }
  if(!is_array($weObj->Message(''))){
    $weObj->text(variable_get("wechat_default_message", "Hi, WeChat!"));
  }
  $weObj->reply();
  exit;
}